import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Goyone",
  description: "Generated by create next app",
};
const ginoraSans = localFont({
  src: [
    {
      path: "../public/fonts/Ginóra Sans Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Ginóra Sans Light Oblique.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/fonts/Ginóra Sans Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Ginóra Sans Oblique.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/Ginóra Sans Semi Bold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Ginóra Sans Semi Bold Oblique.otf",
      weight: "600",
      style: "italic",
    },
    {
      path: "../public/fonts/Ginóra Sans Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Ginóra Sans Bold Oblique.otf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-ginora",
  display: "swap",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ginoraSans.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
